### ISSUE TITLE
Cant Swap newly created pairs

### ISSUE THREAD

**Issue by sanjulaonline** [solxtence/solana-swap#6]
When i'm going to perform a swap in newly launched token, this error will appear from the api

"`Error response from swap API: {'error': 'ApiError', 'errorCode': 'COULD_NOT_FIND_ANY_ROUTE', 'message': 'COULD NOT FIND ANY ROUTE', 'statusCode': 400}`"

**Comment by solxtence** [comment]
This error means the API couldn't find the token.
this can sometimes be solved by changing the transaction type to `v0`

**Comment by sanjulaonline** [comment]
> This error means the API couldn't find the token. this can sometimes be solved by changing the transaction type to `v0`

but after apply v0, there is 500 error appear, cant solve

**Comment by desprdo** [comment]
Can I have the full error message?
