### ISSUE TITLE
Sell to SOL

### ISSUE THREAD

**Issue by fraktal100x** [solxtence/solana-swap#7]
Hi , how can I swap from a token back to SOL? I have tried in many ways and always get: Error getting swap instructions: COULD NOT FIND ANY ROUTE.

**Comment by solxtence** [comment]
Try requesting a versioned transaction by setting txType to v0

**Comment by AmmarKhawaja** [comment]
Hello I am getting the same error, have tried setting txType to v0 but not sure if I did it correctly:

```
const swapResponse = await solanaSwap.getSwapInstructions(
        fromToken, // From Token (SOL)
        toToken, // To Token (example)
        amountSol, // Amount to swap
        slippagePercent, // Slippage tolerance (in percentage)
        keypair.publicKey.toBase58(),
        priorityFee, // Priority fee
        undefined,
        { txType: 'v0' }
    );
```
