### ISSUE TITLE
error message: 'THE TOKEN 7K23LVKPSEXFVZL6LE7N7UGWTLDEGHGFT7AXNHY3UD4P IS NOT TRADABLE'

### ISSUE THREAD

**Issue by malboyoo** [solxtence/solana-swap#8]
**Describe the bug**

i just created a token on pump.fun, you can see it here:
https://bullx.io/terminal?chainId=1399811149&address=7K23LvKpsexfvzL6LE7n7UgWTLDegHGft7AXnhy3Ud4p

swapResponse result into a error message:
'THE TOKEN 7K23LVKPSEXFVZL6LE7N7UGWTLDEGHGFT7AXNHY3UD4P IS NOT TRADABLE'

related function:
```typescript

export const buyToken = async (solAmount: number, tokenAddress: string, private_key: string) => {
  console.log("Buying token with", solAmount, "SOL");
  const useJito = false;
  const fromKeypair = Keypair.fromSecretKey(bs58.decode(private_key));
  const solanaSwap = new SolanaSwap(fromKeypair, "https://api.mainnet-beta.solana.com");
  const swapResponse = await solanaSwap.getSwapInstructions(
    "So11111111111111111111111111111111111111112", // From Token (SOL)
    tokenAddress, // To Token (example)
    solAmount, // Amount to swap
    20, // Slippage tolerance (in percentage)
    fromKeypair.publicKey.toBase58(),
    0.001, // Priority fee
    undefined 
  );
  console.log("Swap response:", swapResponse);
  try {
    const txid = await solanaSwap.performSwap(swapResponse as SwapResponse, {
      sendConfig: { skipPreflight: true },
      maxConfirmationAttempts: 30,
      confirmationTimeout: 500,
      commitmentLevel: "processed",
      useJito,
    });

    console.log("TX Hash:", txid);
    console.log("TX on Solscan:", `https://solscan.io/tx/${txid}`);
  } catch (error: any) {
    console.error("Error while performing the swap:", error.message);
  }
};

```

Swap response:
```

Swap response: {
  error: 'ApiError',
  errorCode: 'TOKEN_NOT_TRADABLE',
  message: 'THE TOKEN 7K23LVKPSEXFVZL6LE7N7UGWTLDEGHGFT7AXNHY3UD4P IS NOT TRADABLE',
  statusCode: 400
}
Error while performing the swap: Cannot read properties of undefined (reading 'serializedTx')

```

I'm not sure if i'm doing something wrong, but this message seem to be a token problem ? but it's a pump fun token so it cant be not tradable ?

I check every argument on the function, they're exact, the rest is veryclose of what you give in the readme.

Thanks for your help.

**Comment by solxtence** [comment]
Hi there,
The bullx link just led me to an empty page.
Also checked your token on solscan and nothing was there.

Are you sure that you are using the correct mint id?

**Comment by malboyoo** [comment]
The token is here and was created yesturday:
https://solscan.io/token/7K23LvKpsexfvzL6LE7n7UgWTLDegHGft7AXnhy3Ud4p

idk why but today this is working fine, il change nothing except a console.log to show the token address, pretty weird, maybe i got an empty space or something in the string.

thanks for your help!
